services:

  idp:
    build: .
    command: ["gunicorn", "--bind", "0.0.0.0:9000", "--access-logfile", "-", "--error-logfile", "-", "oidc_prod_lab:create_idp()"]
    ports:
      - "9000:9000"

  sp:
    build: .
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "--access-logfile", "-", "--error-logfile", "-", "oidc_prod_lab:create_sp()"]
    ports:
      - "8000:8000"
    depends_on:
      - idp
